name: MyWarps
description: Allows players to pay to create and manage their own warps.

author: SavageAvocado.
website: savagedev.net

depend: [Essentials, Vault]
main: net.savagedev.mywarps.MyWarps
version: 0.1

commands:
  mywarps:
    description: Primary command for MyWarps.
